name: CI Pipeline

on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.JS
              uses: actions/setup-node@v3
              with:
                node-version: "6"

            - name: Install Dependencies
              run: npm install --lagacy-peer-deps

            - name: Build project
              run: npm run build